version: '3'

services:
  nginx:
    image: kenmurakii/kro-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - nuxt
      - golang
  nuxt:
    image: kenmurakii/kro-nuxt:latest
    ports:
      - "3000:3000"
  golang:
    image: kenmurakii/kro-golang:latest
    ports:
      - "8082:8082"
